### PR TITLE
Run Script: create mount directories for GeoServer

### LINKED ISSUE #105: Ensure geoserver_mnt folders are created if not existing
Since the `geoserver_mnt` is no more under version control (see #100) I am discovering the following when starting the stack on a cleaned setup:

GeoServer service does not start anymore saying `invalid mount config for type "bind": bind source path does not exist` . In case I manually create  `geoserver_mnt/geoserver_data` and `geoserver_mnt/raster_data` GeoServer starts up well.

Due to https://github.com/docker/compose/issues/2781 our shorthand syntax `./geoserver_mnt/geoserver_data:/opt/geoserver_data/:Z` should create the mount folders if not existing, but they are not as described above. I am pretty sure this was the case in the past. Maybe something changed here?

Maybe having a script creating the folders `geoserver_mnt/geoserver_data` and `geoserver_mnt/raster_data` if not existing might be an option.

### PR DESCRIPTION
**Pull request by JakobMiksch**
fixes #105 

Adapt the `build-and-start.sh` script to create the mount directories for GeoServer.

### CODE REVIEW

**Review by chrismayer — COMMENTED** [review]
`mkdir` does not overwrite any existing data in case `geoserver_mnt/geoserver_data` and `geoserver_mnt/raster_data` exists, right?

**Comment by JakobMiksch** [comment]
@chrismayer no, `mkdir` does not overwrite. I tested it.

**Review by chrismayer — APPROVED** [review]

**Comment by JakobMiksch** [comment]
@jdk24 is this change okay?

**Review by jdk24 — APPROVED** [review]
Thanks! LGTM and please merge at will.

**Pull request merged**
