### PR TITLE
Fix PostGIS Store creation

### PR DESCRIPTION
**Pull request by JakobMiksch**
This PR fixes the creation of the PostGIS store. No workaround like described in #117 or https://github.com/meggsimum/geoserver-node-client/issues/31

- The actual fix happens in `geoserver-node-client`. This PR uses the upgraded version and adapts the code in `geoserver_init`
- from now we include `geoserver-node-client` via NPM releases and not from the git repository anymore

From now on, when the stack is freshly deployed, the layer `station_data:fv_stations` should run out-of-the-box.
@jdk24 could you verify this on your setup?

### CODE REVIEW

**Comment by jdk24** [comment]
Thanks!
After deleting geoserver_mnt, the layer appears to be created successfully for me. [GS init log](https://github.com/meggsimum/sauber-sdi-docker/files/6879960/_sauber-stack_geoserver_init.1.oxdjo5f8mqfe2m44slbwaqo10_logs.txt)
However, trying to access the layer via WMS, WFS, etc. I'm getting a 404 - not found error. 
[The GS log](https://github.com/meggsimum/sauber-sdi-docker/files/6879971/gs_log.txt) seems ok, see last 3 lines.
Did this occur for you?

**Comment by JakobMiksch** [comment]
@jdk24 this did not happen to me. When I opened the layer the first time I got `Internal error Schema <<MY_WORKSPACE>>does not exist. `

I am bit confused, the `geoserver_init` file says that it failed to create `fv_station`. But you are still seeing it?

**Comment by jdk24** [comment]
@JakobMiksch  The layers did show up somehow in the UI, but clicking them produced error 404. 
Trying to publish a layer manually from the station_data:db store gives [this log](https://github.com/meggsimum/sauber-sdi-docker/files/6883395/gs_logs_202107210704.txt).

**Review by jdk24 — APPROVED** [review]

**Comment by chrismayer** [comment]
I just tested this on a cleaned setup and the logs seem OK

```
##############################################################
Start initalizing SAUBER GeoServer...
##############################################################

--------------------------------------------------------------
Creating workspaces...
--------------------------------------------------------------
Configuring the workspaces station_data,image_mosaics

Successfully created workspace station_data

Successfully created workspace image_mosaics

Set proxy base url to "https://sauber-sdi.meggsimum.de/geoserver"

--------------------------------------------------------------
Creating PostGIS data store...
--------------------------------------------------------------

Successfully created PostGIS store station_data

--------------------------------------------------------------
eating stations layer...
--------------------------------------------------------------

WS: station_data, DS: station_data, NATIVE: fv_stations, NAME: fv_stations, TITLE: All Stations
Successfully created stations layer fv_stations

##############################################################
... DONE initalizing SAUBER GeoServer
##############################################################
```

**Pull request merged**
