### PR TITLE
Upgrade GeoServer to v2.19.1

### LINKED ISSUE #78: Upgrade GeoServer to currently stable version (2.19.x)
The GeoServer image used in our stack is officially no more supported. We should upgrade to the currently stable version ([2.19.x](https://hub.docker.com/layers/meggsimum/geoserver/2.19.0/images/sha256-018884c3551a6abb5be7a60d6d909c1660625d8cb43909a80432694cccac182c?context=explore)). Ideally this shouldn't be a big deal :crossed_fingers:

### PR DESCRIPTION
**Pull request by chrismayer**
Upgrades GeoServer to current stable version 2.19.1.

Closes #78

### CODE REVIEW

**Comment by JakobMiksch** [comment]
@chrismayer Looks good. Please merge.

**Review by JakobMiksch — APPROVED** [review]

**Review by JakobMiksch — CHANGES_REQUESTED** [review]
after running `bash build-and-start.sh` the GeoServer did not show up

**Comment by chrismayer** [comment]
I don't think it is related to the GeoServer upgrade. It looks more like the problem I am having for a few days in my local setup, that GeoServer is not reachable (for unknown reasons). But this also happens with v2.17. Have you been on an old setup / outdated images?

**Comment by JakobMiksch** [comment]
I will check if my images are outdated

**Review by jdk24 — APPROVED** [review]
GeoServer 2.19.1 does spool up successfully for me. The issue mentioned by @JakobMiksch did occur and then went away on my local stack as well, though unrelated to this PR. 

gs_19

**Review by JakobMiksch — APPROVED** [review]
@chrismayer It finally worked for me. Please merge.

**Comment by chrismayer** [comment]
Thanks for the reviews guys!

**Pull request merged**
